<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    public function categories()
    {
        return $this->hasMany('App\ProductCategory' ,'product_id');
    }

    public function cuts()
    {
        return $this->hasMany('App\ProductCut' ,'product_id');
    }

    public function accessories()
    {
        return $this->hasMany('App\ProductAccessory' ,'product_id');
    }

    public function discounts()
    {
        return $this->hasMany('App\ProductDiscount' ,'product_id');
    }

    public function days()
    {
        return $this->hasMany('App\ProductActiveDay' ,'product_id');
    }

    public function delete()
    {
        @unlink(storage_path('uploads/products').'/'.$this->image);

        $this->categories()->delete();
        $this->discounts()->delete();
        $this->cuts()->delete();
        $this->accessories()->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
