<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Testimonial extends Model
{
    //
    public function delete()
    {
        @unlink(storage_path('uploads/testimonials/') .$this->image);

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
